version: "3.8"

services:
  java:
    build: .                        # Usa el Dockerfile personalizado
    container_name: minecraft-java
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    restart: unless-stopped
    healthcheck:
      disable: true
